artifact_location: file:///D:/UNI/Semester%207/MLOPs/Assignments/mlops-kubeflow-assignment/mlruns/0
creation_time: 1764417484451
experiment_id: '0'
last_update_time: 1764417484451
lifecycle_stage: active
name: Default
