artifact_location: file:///D:/UNI/Semester%207/MLOPs/Assignments/mlops-kubeflow-assignment/mlruns/325776742626257246
creation_time: 1764417484475
experiment_id: '325776742626257246'
last_update_time: 1764417631624
lifecycle_stage: deleted
name: Boston Housing Prediction
tags: {}
