artifact_location: file:///D:/UNI/Semester%207/MLOPs/Assignments/mlops-kubeflow-assignment/mlruns/168844658784835934
creation_time: 1764417827770
experiment_id: '168844658784835934'
last_update_time: 1764417827770
lifecycle_stage: active
name: Boston Housing Prediction
