artifact_location: file:///D:/UNI/Semester%207/MLOPs/Assignments/mlops-kubeflow-assignment/mlruns/326821872447928796
creation_time: 1764417770124
experiment_id: '326821872447928796'
last_update_time: 1764417770124
lifecycle_stage: active
name: Boston Housing ML Pipeline
